### ISSUE TITLE
 Develop Customer Controller Class

### ISSUE THREAD

**Issue by pravat982** [Abinashkjcjanscinanconanc/moshop#22]
Use controller folder for class 
Develop a CustomerController class  With following details

- createCustomer(Customer Customer): void
- getCustomers(): List<Customer>
- getCustomer(String customerId): Customer
- deleteCustomer(String customerId): void
- updateCustomer(String customerId, Customer Customer): void
- countAll(): long
- getActiveCustomer(): List<Customer>
- customerLogin(String email, String password): Customer

**Comment by Abinashkjcjanscinanconanc** [comment]
Duplicate ticket
#26
